/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopLevelMenu.java
 *
 * Created on Jan 31, 2011, 2:29:18 PM
 */

package chocansimulator;

import chocansimulator.datamangement.BillManager;
import chocansimulator.datamangement.Id;
import chocansimulator.datamangement.Member;
import chocansimulator.datamangement.MemberManager;
import chocansimulator.datamangement.ServiceCode;
import chocansimulator.datamangement.ServiceCodeManager;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author debbj
 */
public class ChocAnUserInterface extends javax.swing.JFrame {
    public static final String chocAnDataDir = "chocAnData";
    public static final String chocAnReportsDir = "chocAnData/Reports";
    public static final String chocAnMemberData = chocAnDataDir + "/member.dat";
    public static final String chocAnId = chocAnDataDir + "/id.dat";
    public static final String chocAnServiceData = chocAnDataDir + "/svc.dat";
    public static final String chocAnProviderData = chocAnDataDir + "/provider.dat";
    public static final String chocAnBillData = chocAnDataDir + "/bill.dat";
    public static final char chocAnFileDelimiter = '^';

    /** Creates new form TopLevelMenu */
    public ChocAnUserInterface() {
        
        initComponents();
        initChocAn();
        testIt();

    }

    public void initChocAn() {
        //MemberManager mm = new MemberManager("/home/debbj/member.dat");
        System.out.println("User.dir: " + System.getProperty("user.dir"));
        
        File file = new File(chocAnReportsDir);
        if ( !file.exists())
            file.mkdirs();

       // Id id = new Id(chocAnId);
        /*
        File directory = new File (".");
        try {
            System.out.println ("Current directory's canonical path: "
                + directory.getCanonicalPath());
            System.out.println ("Current directory's absolute  path: "
                + directory.getAbsolutePath());
        }catch(Exception e) {
            System.out.println("Exceptione is ="+e.getMessage());
        }
         *
         */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ChocAnPanel = new javax.swing.JTabbedPane();
        MemberTabbedPanel = new javax.swing.JPanel();
        ProviderTabbedPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        ServiceCodeTabbedPanel = new javax.swing.JPanel();
        svcCodeTabbedPane = new javax.swing.JTabbedPane();
        svcCodeAddPanel = new javax.swing.JPanel();
        descLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        descText = new javax.swing.JTextField();
        feeText = new javax.swing.JTextField();
        svcCodeAddButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ReportsTabbedPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TerminalTabbedPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        GlobalMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHOCHOLICS");

        ChocAnPanel.setMinimumSize(new java.awt.Dimension(108, 140));
        ChocAnPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChocAnPanelFocusGained(evt);
            }
        });

        javax.swing.GroupLayout MemberTabbedPanelLayout = new javax.swing.GroupLayout(MemberTabbedPanel);
        MemberTabbedPanel.setLayout(MemberTabbedPanelLayout);
        MemberTabbedPanelLayout.setHorizontalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        MemberTabbedPanelLayout.setVerticalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        ChocAnPanel.addTab("Member", MemberTabbedPanel);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Add", jPanel6);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Update", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Delete", jPanel11);

        javax.swing.GroupLayout ProviderTabbedPanelLayout = new javax.swing.GroupLayout(ProviderTabbedPanel);
        ProviderTabbedPanel.setLayout(ProviderTabbedPanelLayout);
        ProviderTabbedPanelLayout.setHorizontalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProviderTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        ProviderTabbedPanelLayout.setVerticalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProviderTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        ChocAnPanel.addTab("Provider", ProviderTabbedPanel);

        svcCodeTabbedPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                svcCodeTabbedPaneFocusGained(evt);
            }
        });

        descLabel.setText("Description:");

        feeLabel.setText("Fee:");

        descText.setText(" ");

        feeText.setText(" ");

        svcCodeAddButton.setText("Add");
        svcCodeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcCodeAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout svcCodeAddPanelLayout = new javax.swing.GroupLayout(svcCodeAddPanel);
        svcCodeAddPanel.setLayout(svcCodeAddPanelLayout);
        svcCodeAddPanelLayout.setHorizontalGroup(
            svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcCodeAddPanelLayout.createSequentialGroup()
                .addGroup(svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcCodeAddPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addComponent(feeLabel))
                        .addGap(26, 26, 26)
                        .addGroup(svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(feeText)
                            .addComponent(descText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(svcCodeAddPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(svcCodeAddButton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        svcCodeAddPanelLayout.setVerticalGroup(
            svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcCodeAddPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descLabel)
                    .addComponent(descText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(svcCodeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feeLabel)
                    .addComponent(feeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(svcCodeAddButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        svcCodeTabbedPane.addTab("Add", svcCodeAddPanel);

        jLabel12.setText("Service Code:");

        jLabel13.setText("Description:");

        jLabel14.setText("Fee:");

        jTextField9.setText(" ");

        jTextField10.setText(" ");
        jTextField10.setMaximumSize(new java.awt.Dimension(20, 20));

        jTextField11.setText(" ");

        jButton10.setText("Search");

        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jButton10))
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton11)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton11)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        svcCodeTabbedPane.addTab("Update", jPanel7);

        jLabel6.setText("Service Code:");

        jLabel7.setText("Description:");

        jLabel8.setText("Fee:");

        jTextField3.setText(" ");

        jTextField4.setText(" ");

        jTextField5.setText(" ");

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jButton7))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton8)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        svcCodeTabbedPane.addTab("Delete", jPanel8);

        javax.swing.GroupLayout ServiceCodeTabbedPanelLayout = new javax.swing.GroupLayout(ServiceCodeTabbedPanel);
        ServiceCodeTabbedPanel.setLayout(ServiceCodeTabbedPanelLayout);
        ServiceCodeTabbedPanelLayout.setHorizontalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svcCodeTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        ServiceCodeTabbedPanelLayout.setVerticalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svcCodeTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Service Code", ServiceCodeTabbedPanel);

        jButton3.setText("Run Member Report");

        jButton4.setText("Run EFT Report");

        jButton5.setText("Run Summary Report");

        jButton6.setText("Run Provider Report");

        javax.swing.GroupLayout ReportsTabbedPanelLayout = new javax.swing.GroupLayout(ReportsTabbedPanel);
        ReportsTabbedPanel.setLayout(ReportsTabbedPanelLayout);
        ReportsTabbedPanelLayout.setHorizontalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(51, 51, 51)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        ReportsTabbedPanelLayout.setVerticalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Reports", ReportsTabbedPanel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Validate Member", "Validate Provider", "Validate Service Code", "Request Service Directory", "Send Bill" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Number");

        jButton1.setText("Run");

        javax.swing.GroupLayout TerminalTabbedPanelLayout = new javax.swing.GroupLayout(TerminalTabbedPanel);
        TerminalTabbedPanel.setLayout(TerminalTabbedPanelLayout);
        TerminalTabbedPanelLayout.setHorizontalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        TerminalTabbedPanelLayout.setVerticalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Terminal", TerminalTabbedPanel);

        GlobalMessageLabel.setText("Message Field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(GlobalMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(ChocAnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ChocAnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(GlobalMessageLabel)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChocAnPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChocAnPanelFocusGained
        jLabel5.setVisible(false);
        jTextField2.setVisible(false);
        providerDeleteButton.setVisible(false);
        addProviderPanel.setVisible(false);
        //System.out.println("in tabbed panel 2 focus gained");
        GlobalMessageLabel.setText("Message Field");
    }

    private void testIt() {

        MemberManager mm = new MemberManager(chocAnMemberData);
        System.out.println("AFTER READ");
        mm.print();
        System.out.println("***");
        boolean deleteData = mm.deleteData(777);
        deleteData = mm.deleteData(83);
        System.out.println("AFTER DELETE");
        System.out.println("***");
        Member mr = new Member();
        mr.setAddress("new address");
        mr.setName("new Name");
        mr.setZip(92722);
        mr.setCity("hillsboro");
        mr.setState("XX");
        mm.addData(mr);
        System.out.println("AFTER Insert of a new member");
        mm.print();
        try {
            mm.writeFile();
        } catch (IOException ex) {
            Logger.getLogger(ChocAnUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

        ServiceCodeManager svcM = new ServiceCodeManager(chocAnServiceData);
        //svcM.print();

        ServiceCode tempSVC = new ServiceCode();
        tempSVC.setDescription("test");
        tempSVC.setFee((float) 21.99);
        svcM.addData(tempSVC);
        svcM.print();

        tempSVC = new ServiceCode();
        tempSVC.setDescription("test2");
        tempSVC.setFee((float) 22.99);
        svcM.addData(tempSVC);
        svcM.print();

        try {
            Id.singletonId(ChocAnUserInterface.chocAnId).destroy();
        } catch (IOException ex) {
            Logger.getLogger(ChocAnUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

        BillManager bm = new BillManager(chocAnBillData);

    }//GEN-LAST:event_ChocAnPanelFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

    private void svcCodeTabbedPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_svcCodeTabbedPaneFocusGained
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jButton8.setVisible(false);
    }//GEN-LAST:event_svcCodeTabbedPaneFocusGained

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if ( jLabel7.isVisible() ) {
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jButton8.setVisible(false);
        } else {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jButton8.setVisible(true);

        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton11ActionPerformed

    private void svcCodeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcCodeAddButtonActionPerformed
        int num = Id.singletonId(ChocAnUserInterface.chocAnId).getProviderId();

        String wrkStr = new String();

        wrkStr = "Num: " + num + " Service:" + descText.getText() + " Fee: " +
                feeText.getText() + " added.";
        GlobalMessageLabel.setText(wrkStr);
    }//GEN-LAST:event_svcCodeAddButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //public static Id number;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ChocAnUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ChocAnPanel;
    private javax.swing.JLabel GlobalMessageLabel;
    private javax.swing.JPanel MemberTabbedPanel;
    private javax.swing.JPanel ProviderTabbedPanel;
    private javax.swing.JPanel ReportsTabbedPanel;
    private javax.swing.JPanel ServiceCodeTabbedPanel;
    private javax.swing.JPanel TerminalTabbedPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descText;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JTextField feeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton svcCodeAddButton;
    private javax.swing.JPanel svcCodeAddPanel;
    private javax.swing.JTabbedPane svcCodeTabbedPane;
    // End of variables declaration//GEN-END:variables

}
