/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopLevelMenu.java
 *
 * Created on Jan 31, 2011, 2:29:18 PM
 */

package chocansimulator;

import chocansimulator.datamangement.BillManager;
import chocansimulator.datamangement.Id;
import chocansimulator.datamangement.Member;
import chocansimulator.datamangement.MemberManager;
import chocansimulator.datamangement.ProviderManager;
import chocansimulator.datamangement.ServiceCode;
import chocansimulator.datamangement.ServiceCodeManager;
import chocansimulator.reports.MemberReport;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author debbj
 */
public class ChocAnUserInterface extends javax.swing.JFrame {
    public static final String chocAnDataDir = "chocAnData";
    public static final String chocAnReportsDir = "chocAnData/Reports";
    public static final String chocAnMemberData = chocAnDataDir + "/member.dat";
    public static final String chocAnId = chocAnDataDir + "/id.dat";
    public static final String chocAnServiceData = chocAnDataDir + "/svc.dat";
    public static final String chocAnProviderData = chocAnDataDir + "/provider.dat";
    public static final String chocAnBillData = chocAnDataDir + "/bill.dat";
    public static final char chocAnFileDelimiter = '^';
    public static final ServiceCodeManager svcMan = new ServiceCodeManager(chocAnServiceData);
    public static final MemberManager memberMan = new MemberManager(chocAnMemberData);
    public static final ProviderManager providerMan = new ProviderManager(chocAnProviderData);
    public static final BillManager billMan = new BillManager(chocAnBillData);

    /** Creates new form TopLevelMenu */
    public ChocAnUserInterface() {
        
        initComponents();
        initChocAn();
        //testIt();

    }

    public void initChocAn() {
        //MemberManager mm = new MemberManager("/home/debbj/member.dat");
        System.out.println("User.dir: " + System.getProperty("user.dir"));
        
        File file = new File(chocAnReportsDir);
        if ( !file.exists())
            file.mkdirs();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChocAnPanel = new javax.swing.JTabbedPane();
        MemberTabbedPanel = new javax.swing.JPanel();
        memberDataManagerPanels = new javax.swing.JTabbedPane();
        memberAddPanel = new javax.swing.JPanel();
        memberAddNameLabel = new javax.swing.JLabel();
        memberAddAddressLabel = new javax.swing.JLabel();
        memberAddCityLabel = new javax.swing.JLabel();
        memberAddStateLabel = new javax.swing.JLabel();
        memberAddZipLabel = new javax.swing.JLabel();
        memberAddNameText = new javax.swing.JTextField();
        memberAddAddressText = new javax.swing.JTextField();
        memberAddCityText = new javax.swing.JTextField();
        memberAddStateText = new javax.swing.JTextField();
        memberAddZipText = new javax.swing.JTextField();
        memberAddButton = new javax.swing.JButton();
        memberAddClearButton = new javax.swing.JButton();
        memberUpdatePanel = new javax.swing.JPanel();
        memberUpNameLabel = new javax.swing.JLabel();
        memberUpAddressLabel = new javax.swing.JLabel();
        memberUpCityLabel = new javax.swing.JLabel();
        memberUpStateLabel = new javax.swing.JLabel();
        memberUpZipLabel = new javax.swing.JLabel();
        memberUpNameText = new javax.swing.JTextField();
        memberUpAddressText = new javax.swing.JTextField();
        memberUpCityText = new javax.swing.JTextField();
        memberUpStateText = new javax.swing.JTextField();
        memberUpZipText = new javax.swing.JTextField();
        memberUpdateButton = new javax.swing.JButton();
        memberUpClearButton = new javax.swing.JButton();
        memberUpNumLabel = new javax.swing.JLabel();
        memberUpNumText = new javax.swing.JTextField();
        memberUpSearchButton = new javax.swing.JButton();
        memberDeletePanel = new javax.swing.JPanel();
        memberDelNameLabel = new javax.swing.JLabel();
        memberDelAddressLabel = new javax.swing.JLabel();
        memberDelCityLabel = new javax.swing.JLabel();
        memberDelStateLabel = new javax.swing.JLabel();
        memberDelZipLabel = new javax.swing.JLabel();
        memberDelNameText = new javax.swing.JTextField();
        memberDelAddressText = new javax.swing.JTextField();
        memberDelCityText = new javax.swing.JTextField();
        memberDelStateText = new javax.swing.JTextField();
        memberDelZipText = new javax.swing.JTextField();
        memberDeleteButton = new javax.swing.JButton();
        memberDelClearButton = new javax.swing.JButton();
        memberDelNumLabel = new javax.swing.JLabel();
        memberDelNumText = new javax.swing.JTextField();
        memberDelSearchButton = new javax.swing.JButton();
        ProviderTabbedPanel = new javax.swing.JPanel();
        ServiceCodeTabbedPanel = new javax.swing.JPanel();
        svcDataManagerPanels = new javax.swing.JTabbedPane();
        svcAddPanel = new javax.swing.JPanel();
        descLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        svcAddDescText = new javax.swing.JTextField();
        svcAddFeeText = new javax.swing.JTextField();
        svcAddButton = new javax.swing.JButton();
        svcAddClearButton = new javax.swing.JButton();
        svcUpdatePanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        svcUpNumLabel = new javax.swing.JLabel();
        svcUpDescLabel = new javax.swing.JLabel();
        svcUpFeeLabel = new javax.swing.JLabel();
        svcUpNumText = new javax.swing.JTextField();
        svcUpDescText = new javax.swing.JTextField();
        svcUpFeeText = new javax.swing.JTextField();
        svcUpSearchButton = new javax.swing.JButton();
        svcUpdateButton = new javax.swing.JButton();
        svcUpdateClearButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        svcDelNumLabel = new javax.swing.JLabel();
        svcDelDescLabel = new javax.swing.JLabel();
        svcDelFeeLabel = new javax.swing.JLabel();
        svcDelNumText = new javax.swing.JTextField();
        svcDelDescText = new javax.swing.JTextField();
        svcDelFeeText = new javax.swing.JTextField();
        svcDelSearchButton = new javax.swing.JButton();
        svcDeleteButton = new javax.swing.JButton();
        svcDelClearButton = new javax.swing.JButton();
        ReportsTabbedPanel = new javax.swing.JPanel();
        memberRptButton = new javax.swing.JButton();
        eftRptButton = new javax.swing.JButton();
        summaryRptButton = new javax.swing.JButton();
        providerRptButton = new javax.swing.JButton();
        TerminalTabbedPanel = new javax.swing.JPanel();
        terminalComboBox = new javax.swing.JComboBox();
        terminalNumLabel = new javax.swing.JLabel();
        terminalNumTextField = new javax.swing.JTextField();
        terminalRunButton = new javax.swing.JButton();
        globalMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHOCHOLICS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                exitChocAn(evt);
            }
        });

        ChocAnPanel.setMinimumSize(new java.awt.Dimension(108, 140));

        memberAddNameLabel.setText("Name:");

        memberAddAddressLabel.setText("Address:");

        memberAddCityLabel.setText("City:");

        memberAddStateLabel.setText("State:");

        memberAddZipLabel.setText("Zip:");

        memberAddButton.setText("Add");
        memberAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberAddButtonActionPerformed(evt);
            }
        });

        memberAddClearButton.setText("Clear");
        memberAddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberAddClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberAddPanelLayout = new javax.swing.GroupLayout(memberAddPanel);
        memberAddPanel.setLayout(memberAddPanelLayout);
        memberAddPanelLayout.setHorizontalGroup(
            memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberAddNameLabel)
                    .addComponent(memberAddAddressLabel))
                .addGap(18, 18, 18)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberAddNameText)
                    .addComponent(memberAddAddressText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addComponent(memberAddCityLabel)
                .addGap(6, 6, 6)
                .addComponent(memberAddCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberAddStateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberAddStateText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(memberAddZipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberAddZipText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(memberAddButton)
                .addGap(68, 68, 68)
                .addComponent(memberAddClearButton)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        memberAddPanelLayout.setVerticalGroup(
            memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberAddNameLabel)
                    .addComponent(memberAddNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberAddAddressLabel)
                    .addComponent(memberAddAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberAddCityLabel)
                    .addComponent(memberAddCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberAddZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberAddZipLabel)
                    .addComponent(memberAddStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberAddStateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberAddButton)
                    .addComponent(memberAddClearButton))
                .addContainerGap())
        );

        memberDataManagerPanels.addTab("Add", memberAddPanel);

        memberUpNameLabel.setText("Name:");

        memberUpAddressLabel.setText("Address:");

        memberUpCityLabel.setText("City:");

        memberUpStateLabel.setText("State:");

        memberUpZipLabel.setText("Zip:");

        memberUpdateButton.setText("Update");
        memberUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUpdateButtonActionPerformed(evt);
            }
        });

        memberUpClearButton.setText("Clear");
        memberUpClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUpClearButtonActionPerformed(evt);
            }
        });

        memberUpNumLabel.setText("Number:");

        memberUpSearchButton.setText("Search");
        memberUpSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberUpSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberUpdatePanelLayout = new javax.swing.GroupLayout(memberUpdatePanel);
        memberUpdatePanel.setLayout(memberUpdatePanelLayout);
        memberUpdatePanelLayout.setHorizontalGroup(
            memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(memberUpdateButton)
                .addGap(68, 68, 68)
                .addComponent(memberUpClearButton)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberUpNameLabel)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberUpdatePanelLayout.createSequentialGroup()
                        .addComponent(memberUpNumLabel)
                        .addGap(18, 18, 18)
                        .addComponent(memberUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(memberUpSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberUpdatePanelLayout.createSequentialGroup()
                        .addComponent(memberUpCityLabel)
                        .addGap(6, 6, 6)
                        .addComponent(memberUpCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(memberUpStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberUpStateText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberUpZipLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberUpdatePanelLayout.createSequentialGroup()
                        .addComponent(memberUpAddressLabel)
                        .addGap(18, 18, 18)
                        .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberUpNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(memberUpAddressText, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(memberUpZipText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        memberUpdatePanelLayout.setVerticalGroup(
            memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberUpNumLabel)
                    .addComponent(memberUpSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberUpNameLabel)
                    .addComponent(memberUpNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberUpAddressLabel)
                    .addComponent(memberUpAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberUpZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberUpZipLabel)
                    .addComponent(memberUpStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberUpStateLabel)
                    .addComponent(memberUpCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberUpCityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberUpdateButton)
                    .addComponent(memberUpClearButton))
                .addContainerGap())
        );

        memberDataManagerPanels.addTab("Update", memberUpdatePanel);

        memberDelNameLabel.setText("Name:");

        memberDelAddressLabel.setText("Address:");

        memberDelCityLabel.setText("City:");

        memberDelStateLabel.setText("State:");

        memberDelZipLabel.setText("Zip:");

        memberDeleteButton.setText("Delete");
        memberDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDeleteButtonActionPerformed(evt);
            }
        });

        memberDelClearButton.setText("Clear");
        memberDelClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDelClearButtonActionPerformed(evt);
            }
        });

        memberDelNumLabel.setText("Number:");

        memberDelSearchButton.setText("Search");
        memberDelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberDelSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberDeletePanelLayout = new javax.swing.GroupLayout(memberDeletePanel);
        memberDeletePanel.setLayout(memberDeletePanelLayout);
        memberDeletePanelLayout.setHorizontalGroup(
            memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberDeletePanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(memberDeleteButton)
                .addGap(68, 68, 68)
                .addComponent(memberDelClearButton)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(memberDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberDelNameLabel)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberDeletePanelLayout.createSequentialGroup()
                        .addComponent(memberDelNumLabel)
                        .addGap(18, 18, 18)
                        .addComponent(memberDelNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(memberDelSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberDeletePanelLayout.createSequentialGroup()
                        .addComponent(memberDelCityLabel)
                        .addGap(6, 6, 6)
                        .addComponent(memberDelCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(memberDelStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberDelStateText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberDelZipLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, memberDeletePanelLayout.createSequentialGroup()
                        .addComponent(memberDelAddressLabel)
                        .addGap(18, 18, 18)
                        .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberDelNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(memberDelAddressText, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(memberDelZipText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        memberDeletePanelLayout.setVerticalGroup(
            memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberDelNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberDelNumLabel)
                    .addComponent(memberDelSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberDelNameLabel)
                    .addComponent(memberDelNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberDelAddressLabel)
                    .addComponent(memberDelAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberDelZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberDelZipLabel)
                    .addComponent(memberDelStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberDelStateLabel)
                    .addComponent(memberDelCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberDelCityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberDeleteButton)
                    .addComponent(memberDelClearButton))
                .addContainerGap())
        );

        memberDataManagerPanels.addTab("Delete", memberDeletePanel);

        javax.swing.GroupLayout MemberTabbedPanelLayout = new javax.swing.GroupLayout(MemberTabbedPanel);
        MemberTabbedPanel.setLayout(MemberTabbedPanelLayout);
        MemberTabbedPanelLayout.setHorizontalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        MemberTabbedPanelLayout.setVerticalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberDataManagerPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        ChocAnPanel.addTab("Member", MemberTabbedPanel);

        javax.swing.GroupLayout ProviderTabbedPanelLayout = new javax.swing.GroupLayout(ProviderTabbedPanel);
        ProviderTabbedPanel.setLayout(ProviderTabbedPanelLayout);
        ProviderTabbedPanelLayout.setHorizontalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        ProviderTabbedPanelLayout.setVerticalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        ChocAnPanel.addTab("Provider", ProviderTabbedPanel);

        descLabel.setText("Description:");

        feeLabel.setText("Fee:");

        svcAddDescText.setText(" ");

        svcAddFeeText.setText(" ");

        svcAddButton.setText("Add");
        svcAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcAddButtonActionPerformed(evt);
            }
        });

        svcAddClearButton.setText("Clear");
        svcAddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcAddClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout svcAddPanelLayout = new javax.swing.GroupLayout(svcAddPanel);
        svcAddPanel.setLayout(svcAddPanelLayout);
        svcAddPanelLayout.setHorizontalGroup(
            svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descLabel)
                    .addComponent(feeLabel))
                .addGap(26, 26, 26)
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(svcAddPanelLayout.createSequentialGroup()
                        .addComponent(svcAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(svcAddClearButton))
                    .addComponent(svcAddFeeText)
                    .addComponent(svcAddDescText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        svcAddPanelLayout.setVerticalGroup(
            svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcAddPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(svcAddDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descLabel))
                .addGap(21, 21, 21)
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcAddPanelLayout.createSequentialGroup()
                        .addComponent(svcAddFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(svcAddButton)
                            .addComponent(svcAddClearButton)))
                    .addComponent(feeLabel))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        svcDataManagerPanels.addTab("Add", svcAddPanel);

        svcUpNumLabel.setText("Service Code:");

        svcUpDescLabel.setText("Description:");

        svcUpFeeLabel.setText("Fee:");

        svcUpNumText.setText(" ");

        svcUpDescText.setMaximumSize(new java.awt.Dimension(20, 20));

        svcUpFeeText.setText(" ");

        svcUpSearchButton.setText("Search");
        svcUpSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcUpSearchButtonActionPerformed(evt);
            }
        });

        svcUpdateButton.setText("Update");
        svcUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcUpdateButtonActionPerformed(evt);
            }
        });

        svcUpdateClearButton.setText("Clear");
        svcUpdateClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcUpdateClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(svcUpDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(svcUpNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(svcUpFeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(svcUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(svcUpSearchButton))
                    .addComponent(svcUpFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcUpDescText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(svcUpdateButton)
                .addGap(54, 54, 54)
                .addComponent(svcUpdateClearButton)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpNumLabel)
                    .addComponent(svcUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcUpSearchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpDescLabel)
                    .addComponent(svcUpDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpFeeLabel)
                    .addComponent(svcUpFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpdateButton)
                    .addComponent(svcUpdateClearButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout svcUpdatePanelLayout = new javax.swing.GroupLayout(svcUpdatePanel);
        svcUpdatePanel.setLayout(svcUpdatePanelLayout);
        svcUpdatePanelLayout.setHorizontalGroup(
            svcUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcUpdatePanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        svcUpdatePanelLayout.setVerticalGroup(
            svcUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcUpdatePanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        svcDataManagerPanels.addTab("Update", svcUpdatePanel);

        svcDelNumLabel.setText("Service Code:");

        svcDelDescLabel.setText("Description:");

        svcDelFeeLabel.setText("Fee:");

        svcDelNumText.setText(" ");

        svcDelDescText.setMaximumSize(new java.awt.Dimension(20, 20));

        svcDelFeeText.setText(" ");

        svcDelSearchButton.setText("Search");
        svcDelSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcDelSearchButtonActionPerformed(evt);
            }
        });

        svcDeleteButton.setText("Delete");
        svcDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcDeleteButtonActionPerformed(evt);
            }
        });

        svcDelClearButton.setText("Clear");
        svcDelClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcDelClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(svcDelDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(svcDelNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(svcDelFeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(svcDelNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(svcDelSearchButton))
                    .addComponent(svcDelFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcDelDescText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(svcDeleteButton)
                .addGap(54, 54, 54)
                .addComponent(svcDelClearButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcDelNumLabel)
                    .addComponent(svcDelNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcDelSearchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcDelDescLabel)
                    .addComponent(svcDelDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcDelFeeLabel)
                    .addComponent(svcDelFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcDeleteButton)
                    .addComponent(svcDelClearButton))
                .addContainerGap())
        );

        svcDataManagerPanels.addTab("Delete", jPanel10);

        javax.swing.GroupLayout ServiceCodeTabbedPanelLayout = new javax.swing.GroupLayout(ServiceCodeTabbedPanel);
        ServiceCodeTabbedPanel.setLayout(ServiceCodeTabbedPanelLayout);
        ServiceCodeTabbedPanelLayout.setHorizontalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(svcDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ServiceCodeTabbedPanelLayout.setVerticalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svcDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Service Code", ServiceCodeTabbedPanel);

        memberRptButton.setText("Run Member Report");
        memberRptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberRptButtonActionPerformed(evt);
            }
        });

        eftRptButton.setText("Run EFT Report");
        eftRptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eftRptButtonActionPerformed(evt);
            }
        });

        summaryRptButton.setText("Run Summary Report");
        summaryRptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryRptButtonActionPerformed(evt);
            }
        });

        providerRptButton.setText("Run Provider Report");
        providerRptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerRptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportsTabbedPanelLayout = new javax.swing.GroupLayout(ReportsTabbedPanel);
        ReportsTabbedPanel.setLayout(ReportsTabbedPanelLayout);
        ReportsTabbedPanelLayout.setHorizontalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberRptButton)
                    .addComponent(providerRptButton))
                .addGap(51, 51, 51)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eftRptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaryRptButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        ReportsTabbedPanelLayout.setVerticalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberRptButton)
                    .addComponent(eftRptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerRptButton)
                    .addComponent(summaryRptButton))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Reports", ReportsTabbedPanel);

        terminalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Validate Member", "Validate Provider", "Validate Service Code", "Request Service Directory", "Send Bill" }));
        terminalComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalComboBoxActionPerformed(evt);
            }
        });

        terminalNumLabel.setText("Enter Number");

        terminalRunButton.setText("Run");

        javax.swing.GroupLayout TerminalTabbedPanelLayout = new javax.swing.GroupLayout(TerminalTabbedPanel);
        TerminalTabbedPanel.setLayout(TerminalTabbedPanelLayout);
        TerminalTabbedPanelLayout.setHorizontalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(terminalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                        .addComponent(terminalNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terminalNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(terminalRunButton)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        TerminalTabbedPanelLayout.setVerticalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(terminalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(terminalNumLabel)
                    .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(terminalNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(terminalRunButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Terminal", TerminalTabbedPanel);

        globalMessageLabel.setText("Message Field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(globalMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(438, 438, 438))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ChocAnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ChocAnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(globalMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalComboBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_terminalComboBoxActionPerformed

    private void svcUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcUpdateButtonActionPerformed
        ServiceCode s = null;
        int i = Integer.parseInt(svcUpNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found update not completed.");
        } else {
            s.setDescription(svcUpDescText.getText());

            String wrk = svcUpFeeText.getText();
            float f = Float.valueOf(wrk.trim()).floatValue();
            s.setFee(f);
            globalMessageLabel.setText("Service Code updated.");
        }
        svcUpNumText.setEnabled(true);
}//GEN-LAST:event_svcUpdateButtonActionPerformed

    private void svcAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcAddButtonActionPerformed

        //TODO- validate fields

        ServiceCode tempSvc = new ServiceCode();

        tempSvc.setDescription(svcAddDescText.getText());
        String wrk = svcAddFeeText.getText();
        float f = Float.valueOf(wrk.trim()).floatValue();
        tempSvc.setFee(f);
        svcMan.addData(tempSvc);
        globalMessageLabel.setText("Service Code " + tempSvc.getNumber() +
                                   " has been added");
    }//GEN-LAST:event_svcAddButtonActionPerformed

    private void exitChocAn(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitChocAn
        try {
            Id.singletonId(chocAnId).destroy();
        } catch (IOException ex) {
            //Error handling here
        }


    }//GEN-LAST:event_exitChocAn

    private void svcUpSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcUpSearchButtonActionPerformed
        ServiceCode s = null;
        int i = Integer.parseInt(svcUpNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found.");
        } else {
            svcUpDescText.setText(s.getDescription());
            svcUpFeeText.setText(String.valueOf(s.getFee()));
            globalMessageLabel.setText("Service Code ready for update.");
            svcUpNumText.setEnabled(false);
            svcUpSearchButton.setEnabled(false);
        }

        
    }//GEN-LAST:event_svcUpSearchButtonActionPerformed

    private void svcUpdateClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcUpdateClearButtonActionPerformed

        svcUpDescText.setText("");
        svcUpFeeText.setText("");
        svcUpNumText.setText("");
        svcUpNumText.setEnabled(true);
        svcUpSearchButton.setEnabled(true);
    }//GEN-LAST:event_svcUpdateClearButtonActionPerformed

    private void svcAddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcAddClearButtonActionPerformed
        svcAddDescText.setText("");
        svcAddFeeText.setText("");
    }//GEN-LAST:event_svcAddClearButtonActionPerformed

    private void svcDelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcDelSearchButtonActionPerformed
        ServiceCode s = null;
        int i = Integer.parseInt(svcDelNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found.");
        } else {
            svcDelDescText.setText(s.getDescription());
            svcDelFeeText.setText(String.valueOf(s.getFee()));
            globalMessageLabel.setText("Service Code ready for delete.");
            svcDelNumText.setEnabled(false);
            svcDelSearchButton.setEnabled(false);
        }
    }//GEN-LAST:event_svcDelSearchButtonActionPerformed

    private void svcDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcDeleteButtonActionPerformed

        //TODO- validate fields
        ServiceCode s = null;
        int i = Integer.parseInt(svcDelNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found.");
        } else {
            s.setStatus(0);
            globalMessageLabel.setText("Service Code disabled.");
            svcDelNumText.setEnabled(false);
            svcDelSearchButton.setEnabled(false);
        }
    }//GEN-LAST:event_svcDeleteButtonActionPerformed

    private void svcDelClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcDelClearButtonActionPerformed
        svcDelDescText.setText("");
        svcDelFeeText.setText("");
        svcDelNumText.setText("");
        svcDelNumText.setEnabled(true);
        svcDelSearchButton.setEnabled(true);
    }//GEN-LAST:event_svcDelClearButtonActionPerformed

    private void memberUpSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUpSearchButtonActionPerformed
        Member m = null;
        int i = Integer.parseInt(memberUpNumText.getText().trim());
        m = (Member) memberMan.search(i);
        if (m == null) {
            globalMessageLabel.setText("Member not found.");
        } else {
            memberUpNameText.setText(m.getName());
            memberUpAddressText.setText(m.getAddress());
            memberUpCityText.setText(m.getCity());
            memberUpStateText.setText(m.getState());
            memberUpZipText.setText(String.valueOf(m.getZip()));
            memberUpNumText.setEnabled(false);
            memberUpSearchButton.setEnabled(false);
            globalMessageLabel.setText("Member ready to update.");

        }
}//GEN-LAST:event_memberUpSearchButtonActionPerformed

    private void memberUpClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUpClearButtonActionPerformed
        memberUpNameText.setText("");
        memberUpAddressText.setText("");
        memberUpCityText.setText("");
        memberUpStateText.setText("");
        memberUpZipText.setText("");
        memberUpNumText.setEnabled(true);
        memberUpSearchButton.setEnabled(true);
}//GEN-LAST:event_memberUpClearButtonActionPerformed

    private void memberUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberUpdateButtonActionPerformed
        Member m = null;
        int i = Integer.parseInt(memberUpNumText.getText().trim());
        m = (Member) memberMan.search(i);
        if (m == null) {
            globalMessageLabel.setText("Member not found.");
        } else {
            m.setName(memberUpNameText.getText());
            m.setAddress(memberUpAddressText.getText());
            m.setCity(memberUpCityText.getText());
            m.setState(memberUpStateText.getText());
            int k = Integer.parseInt(memberUpZipText.getText().trim());
            m.setZip(k);
            memberUpNumText.setEnabled(false);
            memberUpSearchButton.setEnabled(false);
            globalMessageLabel.setText("Member has been updated.");

        }
}//GEN-LAST:event_memberUpdateButtonActionPerformed

    private void memberAddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberAddClearButtonActionPerformed
        memberAddNameText.setText("");
        memberAddAddressText.setText("");
        memberAddCityText.setText("");
        memberAddStateText.setText("");
        memberAddZipText.setText("");
}//GEN-LAST:event_memberAddClearButtonActionPerformed

    private void memberAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberAddButtonActionPerformed
        //TODO- validate fields

        Member m = new Member();

        m.setName(memberAddNameText.getText());
        m.setAddress(memberAddAddressText.getText());
        m.setCity(memberAddCityText.getText());
        m.setState(memberAddStateText.getText());
        int i = Integer.parseInt(memberAddZipText.getText().trim());
        m.setZip(i);
        memberMan.addData(m);
        globalMessageLabel.setText("Member " + m.getNumber() +
                " has been added");
}//GEN-LAST:event_memberAddButtonActionPerformed

    private void memberDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDeleteButtonActionPerformed
        Member m = null;
        int i = Integer.parseInt(memberDelNumText.getText().trim());
        m = (Member) memberMan.search(i);
        if (m == null) {
            globalMessageLabel.setText("Member not found.");
        } else {
            m.setStatus(0);
            memberUpNumText.setEnabled(false);
            memberUpSearchButton.setEnabled(false);
            globalMessageLabel.setText("Member has been disabled.");

        }
    }//GEN-LAST:event_memberDeleteButtonActionPerformed

    private void memberDelClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDelClearButtonActionPerformed
        memberDelNameText.setText("");
        memberDelAddressText.setText("");
        memberDelCityText.setText("");
        memberDelStateText.setText("");
        memberDelZipText.setText("");
        memberDelNumText.setEnabled(true);
        memberDelSearchButton.setEnabled(true);
    }//GEN-LAST:event_memberDelClearButtonActionPerformed

    private void memberDelSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberDelSearchButtonActionPerformed
        Member m = null;
        int i = Integer.parseInt(memberDelNumText.getText().trim());
        m = (Member) memberMan.search(i);
        if (m == null) {
            globalMessageLabel.setText("Member not found.");
        } else {
            memberDelNameText.setText(m.getName());
            memberDelAddressText.setText(m.getAddress());
            memberDelCityText.setText(m.getCity());
            memberDelStateText.setText(m.getState());
            memberDelZipText.setText(String.valueOf(m.getZip()));
            memberDelNumText.setEnabled(false);
            memberDelSearchButton.setEnabled(false);
            globalMessageLabel.setText("Member has been found.");

        }
    }//GEN-LAST:event_memberDelSearchButtonActionPerformed

    private void memberRptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberRptButtonActionPerformed
        MemberReport mr = new MemberReport();
        mr.createReport();
        if (mr.createReport()) {
            globalMessageLabel.setText("Member reports are available.");
        } else {
            globalMessageLabel.setText("Member reports could not be run.");
        }
    }//GEN-LAST:event_memberRptButtonActionPerformed

    private void providerRptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerRptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerRptButtonActionPerformed

    private void eftRptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eftRptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eftRptButtonActionPerformed

    private void summaryRptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryRptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_summaryRptButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ChocAnUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ChocAnPanel;
    private javax.swing.JPanel MemberTabbedPanel;
    private javax.swing.JPanel ProviderTabbedPanel;
    private javax.swing.JPanel ReportsTabbedPanel;
    private javax.swing.JPanel ServiceCodeTabbedPanel;
    private javax.swing.JPanel TerminalTabbedPanel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JButton eftRptButton;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JLabel globalMessageLabel;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel memberAddAddressLabel;
    private javax.swing.JTextField memberAddAddressText;
    private javax.swing.JButton memberAddButton;
    private javax.swing.JLabel memberAddCityLabel;
    private javax.swing.JTextField memberAddCityText;
    private javax.swing.JButton memberAddClearButton;
    private javax.swing.JLabel memberAddNameLabel;
    private javax.swing.JTextField memberAddNameText;
    private javax.swing.JPanel memberAddPanel;
    private javax.swing.JLabel memberAddStateLabel;
    private javax.swing.JTextField memberAddStateText;
    private javax.swing.JLabel memberAddZipLabel;
    private javax.swing.JTextField memberAddZipText;
    private javax.swing.JTabbedPane memberDataManagerPanels;
    private javax.swing.JLabel memberDelAddressLabel;
    private javax.swing.JTextField memberDelAddressText;
    private javax.swing.JLabel memberDelCityLabel;
    private javax.swing.JTextField memberDelCityText;
    private javax.swing.JButton memberDelClearButton;
    private javax.swing.JLabel memberDelNameLabel;
    private javax.swing.JTextField memberDelNameText;
    private javax.swing.JLabel memberDelNumLabel;
    private javax.swing.JTextField memberDelNumText;
    private javax.swing.JButton memberDelSearchButton;
    private javax.swing.JLabel memberDelStateLabel;
    private javax.swing.JTextField memberDelStateText;
    private javax.swing.JLabel memberDelZipLabel;
    private javax.swing.JTextField memberDelZipText;
    private javax.swing.JButton memberDeleteButton;
    private javax.swing.JPanel memberDeletePanel;
    private javax.swing.JButton memberRptButton;
    private javax.swing.JLabel memberUpAddressLabel;
    private javax.swing.JTextField memberUpAddressText;
    private javax.swing.JLabel memberUpCityLabel;
    private javax.swing.JTextField memberUpCityText;
    private javax.swing.JButton memberUpClearButton;
    private javax.swing.JLabel memberUpNameLabel;
    private javax.swing.JTextField memberUpNameText;
    private javax.swing.JLabel memberUpNumLabel;
    private javax.swing.JTextField memberUpNumText;
    private javax.swing.JButton memberUpSearchButton;
    private javax.swing.JLabel memberUpStateLabel;
    private javax.swing.JTextField memberUpStateText;
    private javax.swing.JLabel memberUpZipLabel;
    private javax.swing.JTextField memberUpZipText;
    private javax.swing.JButton memberUpdateButton;
    private javax.swing.JPanel memberUpdatePanel;
    private javax.swing.JButton providerRptButton;
    private javax.swing.JButton summaryRptButton;
    private javax.swing.JButton svcAddButton;
    private javax.swing.JButton svcAddClearButton;
    private javax.swing.JTextField svcAddDescText;
    private javax.swing.JTextField svcAddFeeText;
    private javax.swing.JPanel svcAddPanel;
    private javax.swing.JTabbedPane svcDataManagerPanels;
    private javax.swing.JButton svcDelClearButton;
    private javax.swing.JLabel svcDelDescLabel;
    private javax.swing.JTextField svcDelDescText;
    private javax.swing.JLabel svcDelFeeLabel;
    private javax.swing.JTextField svcDelFeeText;
    private javax.swing.JLabel svcDelNumLabel;
    private javax.swing.JTextField svcDelNumText;
    private javax.swing.JButton svcDelSearchButton;
    private javax.swing.JButton svcDeleteButton;
    private javax.swing.JLabel svcUpDescLabel;
    private javax.swing.JTextField svcUpDescText;
    private javax.swing.JLabel svcUpFeeLabel;
    private javax.swing.JTextField svcUpFeeText;
    private javax.swing.JLabel svcUpNumLabel;
    private javax.swing.JTextField svcUpNumText;
    private javax.swing.JButton svcUpSearchButton;
    private javax.swing.JButton svcUpdateButton;
    private javax.swing.JButton svcUpdateClearButton;
    private javax.swing.JPanel svcUpdatePanel;
    private javax.swing.JComboBox terminalComboBox;
    private javax.swing.JLabel terminalNumLabel;
    private javax.swing.JTextField terminalNumTextField;
    private javax.swing.JButton terminalRunButton;
    // End of variables declaration//GEN-END:variables

}
