/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TopLevelMenu.java
 *
 * Created on Jan 31, 2011, 2:29:18 PM
 */

package chocansimulator;

import chocansimulator.datamangement.BillManager;
import chocansimulator.datamangement.Id;
import chocansimulator.datamangement.Member;
import chocansimulator.datamangement.MemberManager;
import chocansimulator.datamangement.ProviderManager;
import chocansimulator.datamangement.ServiceCode;
import chocansimulator.datamangement.ServiceCodeManager;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author debbj
 */
public class ChocAnUserInterface extends javax.swing.JFrame {
    public static final String chocAnDataDir = "chocAnData";
    public static final String chocAnReportsDir = "chocAnData/Reports";
    public static final String chocAnMemberData = chocAnDataDir + "/member.dat";
    public static final String chocAnId = chocAnDataDir + "/id.dat";
    public static final String chocAnServiceData = chocAnDataDir + "/svc.dat";
    public static final String chocAnProviderData = chocAnDataDir + "/provider.dat";
    public static final String chocAnBillData = chocAnDataDir + "/bill.dat";
    public static final char chocAnFileDelimiter = '^';
    public static final ServiceCodeManager svcMan = new ServiceCodeManager(chocAnServiceData);
    public static final MemberManager memberMan = new MemberManager(chocAnMemberData);
    public static final ProviderManager providerMan = new ProviderManager(chocAnProviderData);
    public static final BillManager billMan = new BillManager(chocAnBillData);

    /** Creates new form TopLevelMenu */
    public ChocAnUserInterface() {
        
        initComponents();
        initChocAn();
        //testIt();

    }

    public void initChocAn() {
        //MemberManager mm = new MemberManager("/home/debbj/member.dat");
        System.out.println("User.dir: " + System.getProperty("user.dir"));
        
        File file = new File(chocAnReportsDir);
        if ( !file.exists())
            file.mkdirs();

       // Id id = new Id(chocAnId);
        /*
        File directory = new File (".");
        try {
            System.out.println ("Current directory's canonical path: "
                + directory.getCanonicalPath());
            System.out.println ("Current directory's absolute  path: "
                + directory.getAbsolutePath());
        }catch(Exception e) {
            System.out.println("Exceptione is ="+e.getMessage());
        }
         *
         */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ChocAnPanel = new javax.swing.JTabbedPane();
        MemberTabbedPanel = new javax.swing.JPanel();
        memberDataManagerPanels = new javax.swing.JTabbedPane();
        memberAddPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        stateText = new javax.swing.JTextField();
        zipText = new javax.swing.JTextField();
        memberAddButton = new javax.swing.JButton();
        memberUpdatePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        memberAddPanel1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        cityLabel1 = new javax.swing.JLabel();
        stateLabel1 = new javax.swing.JLabel();
        zipLabel1 = new javax.swing.JLabel();
        nameText1 = new javax.swing.JTextField();
        addressText1 = new javax.swing.JTextField();
        cityText1 = new javax.swing.JTextField();
        stateText1 = new javax.swing.JTextField();
        zipText1 = new javax.swing.JTextField();
        memberAddButton1 = new javax.swing.JButton();
        memberDeletePanel = new javax.swing.JPanel();
        ProviderTabbedPanel = new javax.swing.JPanel();
        ServiceCodeTabbedPanel = new javax.swing.JPanel();
        svcDataManagerPanels = new javax.swing.JTabbedPane();
        svcAddPanel = new javax.swing.JPanel();
        descLabel = new javax.swing.JLabel();
        feeLabel = new javax.swing.JLabel();
        descText = new javax.swing.JTextField();
        feeText = new javax.swing.JTextField();
        svcAddButton = new javax.swing.JButton();
        svcUpdatePanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        svcUpNumLabel = new javax.swing.JLabel();
        svcUpDescLabel = new javax.swing.JLabel();
        svcUpFeeLabel = new javax.swing.JLabel();
        svcUpNumText = new javax.swing.JTextField();
        svcUpDescText = new javax.swing.JTextField();
        svcUpFeeText = new javax.swing.JTextField();
        svcUpSearchButton = new javax.swing.JButton();
        svcUpdateButton = new javax.swing.JButton();
        svcDeletePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ReportsTabbedPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TerminalTabbedPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        globalMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHOCHOLICS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                exitChocAn(evt);
            }
        });

        ChocAnPanel.setMinimumSize(new java.awt.Dimension(108, 140));
        ChocAnPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ChocAnPanelFocusGained(evt);
            }
        });

        nameLabel.setText("Name:");

        addressLabel.setText("Address:");

        cityLabel.setText("City:");

        stateLabel.setText("State:");

        zipLabel.setText("Zip:");

        memberAddButton.setText("Add");

        javax.swing.GroupLayout memberAddPanelLayout = new javax.swing.GroupLayout(memberAddPanel);
        memberAddPanel.setLayout(memberAddPanelLayout);
        memberAddPanelLayout.setHorizontalGroup(
            memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(addressLabel))
                .addGap(18, 18, 18)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameText)
                    .addComponent(addressText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addComponent(cityLabel)
                .addGap(6, 6, 6)
                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zipText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(memberAddButton)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        memberAddPanelLayout.setVerticalGroup(
            memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(memberAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipLabel)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(memberAddButton)
                .addContainerGap())
        );

        memberDataManagerPanels.addTab("Add", memberAddPanel);

        jLabel1.setText("Number:");

        nameLabel1.setText("Name:");

        addressLabel1.setText("Address:");

        cityLabel1.setText("City:");

        stateLabel1.setText("State:");

        zipLabel1.setText("Zip:");

        memberAddButton1.setText("Add");

        javax.swing.GroupLayout memberAddPanel1Layout = new javax.swing.GroupLayout(memberAddPanel1);
        memberAddPanel1.setLayout(memberAddPanel1Layout);
        memberAddPanel1Layout.setHorizontalGroup(
            memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanel1Layout.createSequentialGroup()
                .addGroup(memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1)
                    .addComponent(addressLabel1))
                .addGap(18, 18, 18)
                .addGroup(memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameText1)
                    .addComponent(addressText1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(memberAddPanel1Layout.createSequentialGroup()
                .addComponent(cityLabel1)
                .addGap(6, 6, 6)
                .addComponent(cityText1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stateText1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zipLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zipText1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(memberAddPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(memberAddButton1)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        memberAddPanel1Layout.setVerticalGroup(
            memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberAddPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel1)
                    .addComponent(addressText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(memberAddPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel1)
                    .addComponent(cityText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipLabel1)
                    .addComponent(stateText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(memberAddButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout memberUpdatePanelLayout = new javax.swing.GroupLayout(memberUpdatePanel);
        memberUpdatePanel.setLayout(memberUpdatePanelLayout);
        memberUpdatePanelLayout.setHorizontalGroup(
            memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(memberAddPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        memberUpdatePanelLayout.setVerticalGroup(
            memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberUpdatePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(memberUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberAddPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        memberDataManagerPanels.addTab("Update", memberUpdatePanel);

        javax.swing.GroupLayout memberDeletePanelLayout = new javax.swing.GroupLayout(memberDeletePanel);
        memberDeletePanel.setLayout(memberDeletePanelLayout);
        memberDeletePanelLayout.setHorizontalGroup(
            memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        memberDeletePanelLayout.setVerticalGroup(
            memberDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        memberDataManagerPanels.addTab("Delete", memberDeletePanel);

        javax.swing.GroupLayout MemberTabbedPanelLayout = new javax.swing.GroupLayout(MemberTabbedPanel);
        MemberTabbedPanel.setLayout(MemberTabbedPanelLayout);
        MemberTabbedPanelLayout.setHorizontalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        MemberTabbedPanelLayout.setVerticalGroup(
            MemberTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberDataManagerPanels)
                .addContainerGap())
        );

        ChocAnPanel.addTab("Member", MemberTabbedPanel);

        javax.swing.GroupLayout ProviderTabbedPanelLayout = new javax.swing.GroupLayout(ProviderTabbedPanel);
        ProviderTabbedPanel.setLayout(ProviderTabbedPanelLayout);
        ProviderTabbedPanelLayout.setHorizontalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        ProviderTabbedPanelLayout.setVerticalGroup(
            ProviderTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        ChocAnPanel.addTab("Provider", ProviderTabbedPanel);

        svcDataManagerPanels.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                svcDataManagerPanelsFocusGained(evt);
            }
        });

        descLabel.setText("Description:");

        feeLabel.setText("Fee:");

        descText.setText(" ");

        feeText.setText(" ");

        svcAddButton.setText("Add");
        svcAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout svcAddPanelLayout = new javax.swing.GroupLayout(svcAddPanel);
        svcAddPanel.setLayout(svcAddPanelLayout);
        svcAddPanelLayout.setHorizontalGroup(
            svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcAddPanelLayout.createSequentialGroup()
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcAddPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descLabel)
                            .addComponent(feeLabel))
                        .addGap(26, 26, 26)
                        .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(feeText)
                            .addComponent(descText, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(svcAddPanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(svcAddButton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        svcAddPanelLayout.setVerticalGroup(
            svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcAddPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descLabel))
                .addGap(21, 21, 21)
                .addGroup(svcAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcAddPanelLayout.createSequentialGroup()
                        .addComponent(feeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(svcAddButton))
                    .addComponent(feeLabel))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        svcDataManagerPanels.addTab("Add", svcAddPanel);

        svcUpNumLabel.setText("Service Code:");

        svcUpDescLabel.setText("Description:");

        svcUpFeeLabel.setText("Fee:");

        svcUpNumText.setText(" ");

        svcUpDescText.setMaximumSize(new java.awt.Dimension(20, 20));

        svcUpFeeText.setText(" ");

        svcUpSearchButton.setText("Search");
        svcUpSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcUpSearchButtonActionPerformed(evt);
            }
        });

        svcUpdateButton.setText("Update");
        svcUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(svcUpDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(svcUpNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(svcUpFeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(svcUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(svcUpSearchButton))
                    .addComponent(svcUpFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcUpDescText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(svcUpdateButton)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpNumLabel)
                    .addComponent(svcUpNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svcUpSearchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpDescLabel)
                    .addComponent(svcUpDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svcUpFeeLabel)
                    .addComponent(svcUpFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(svcUpdateButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout svcUpdatePanelLayout = new javax.swing.GroupLayout(svcUpdatePanel);
        svcUpdatePanel.setLayout(svcUpdatePanelLayout);
        svcUpdatePanelLayout.setHorizontalGroup(
            svcUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcUpdatePanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        svcUpdatePanelLayout.setVerticalGroup(
            svcUpdatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcUpdatePanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        svcDataManagerPanels.addTab("Update", svcUpdatePanel);

        jLabel6.setText("Service Code:");

        jLabel7.setText("Description:");

        jLabel8.setText("Fee:");

        jTextField3.setText(" ");

        jTextField4.setText(" ");

        jTextField5.setText(" ");

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout svcDeletePanelLayout = new javax.swing.GroupLayout(svcDeletePanel);
        svcDeletePanel.setLayout(svcDeletePanelLayout);
        svcDeletePanelLayout.setHorizontalGroup(
            svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcDeletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(svcDeletePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svcDeletePanelLayout.createSequentialGroup()
                        .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, svcDeletePanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jButton7))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(248, 248, 248))
            .addGroup(svcDeletePanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton8)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        svcDeletePanelLayout.setVerticalGroup(
            svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(svcDeletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(svcDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        svcDataManagerPanels.addTab("Delete", svcDeletePanel);

        javax.swing.GroupLayout ServiceCodeTabbedPanelLayout = new javax.swing.GroupLayout(ServiceCodeTabbedPanel);
        ServiceCodeTabbedPanel.setLayout(ServiceCodeTabbedPanelLayout);
        ServiceCodeTabbedPanelLayout.setHorizontalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(svcDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ServiceCodeTabbedPanelLayout.setVerticalGroup(
            ServiceCodeTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServiceCodeTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svcDataManagerPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Service Code", ServiceCodeTabbedPanel);

        jButton3.setText("Run Member Report");

        jButton4.setText("Run EFT Report");

        jButton5.setText("Run Summary Report");

        jButton6.setText("Run Provider Report");

        javax.swing.GroupLayout ReportsTabbedPanelLayout = new javax.swing.GroupLayout(ReportsTabbedPanel);
        ReportsTabbedPanel.setLayout(ReportsTabbedPanelLayout);
        ReportsTabbedPanelLayout.setHorizontalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(51, 51, 51)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        ReportsTabbedPanelLayout.setVerticalGroup(
            ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsTabbedPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReportsTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Reports", ReportsTabbedPanel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Validate Member", "Validate Provider", "Validate Service Code", "Request Service Directory", "Send Bill" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Number");

        jButton1.setText("Run");

        javax.swing.GroupLayout TerminalTabbedPanelLayout = new javax.swing.GroupLayout(TerminalTabbedPanel);
        TerminalTabbedPanel.setLayout(TerminalTabbedPanelLayout);
        TerminalTabbedPanelLayout.setHorizontalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        TerminalTabbedPanelLayout.setVerticalGroup(
            TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminalTabbedPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(TerminalTabbedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        ChocAnPanel.addTab("Terminal", TerminalTabbedPanel);

        globalMessageLabel.setText("Message Field");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(globalMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(ChocAnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChocAnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(globalMessageLabel)
                .addGap(185, 185, 185))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChocAnPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChocAnPanelFocusGained
        //jLabel5.setVisible(false);
        //jTextField2.setVisible(false);
        //providerDeleteButton.setVisible(false);
        //addProviderPanel.setVisible(false);
        //System.out.println("in tabbed panel 2 focus gained");
        globalMessageLabel.setText("Message Field");
    }

    private void testIt() {

        MemberManager mm = new MemberManager(chocAnMemberData);
        System.out.println("AFTER READ");
        mm.print();
        System.out.println("***");
        boolean deleteData = mm.deleteData(777);
        deleteData = mm.deleteData(83);
        System.out.println("AFTER DELETE");
        System.out.println("***");
        Member mr = new Member();
        mr.setAddress("new address");
        mr.setName("new Name");
        mr.setZip(92722);
        mr.setCity("hillsboro");
        mr.setState("XX");
        mm.addData(mr);
        System.out.println("AFTER Insert of a new member");
        mm.print();
        try {
            mm.writeFile();
        } catch (IOException ex) {
            Logger.getLogger(ChocAnUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

        //svcMan.print();

        

        BillManager bm = new BillManager(chocAnBillData);

    }//GEN-LAST:event_ChocAnPanelFocusGained

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

    private void svcDataManagerPanelsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_svcDataManagerPanelsFocusGained
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jButton8.setVisible(false);
    }//GEN-LAST:event_svcDataManagerPanelsFocusGained

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if ( jLabel7.isVisible() ) {
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jButton8.setVisible(false);
        } else {
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jButton8.setVisible(true);

        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void svcUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcUpdateButtonActionPerformed
        ServiceCode s = null;
        int i = Integer.parseInt(svcUpNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found update not completed.");
        } else {
            s.setDescription(svcUpDescText.getText());

            String wrk = svcUpFeeText.getText();
            float f = Float.valueOf(wrk.trim()).floatValue();
            s.setFee(f);
            globalMessageLabel.setText("Service Code updated.");
        }
}//GEN-LAST:event_svcUpdateButtonActionPerformed

    private void svcAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcAddButtonActionPerformed

        //ServiceCodeManager svcM = new ServiceCodeManager(chocAnServiceData);

        //TODO- validate fields

        ServiceCode tempSvc = new ServiceCode();

        tempSvc.setDescription(descText.getText());
        String wrk = feeText.getText();
        float f = Float.valueOf(wrk.trim()).floatValue();
        tempSvc.setFee(f);
        svcMan.addData(tempSvc);
        globalMessageLabel.setText("Service Code " + tempSvc.getNumber() +
                                   " has been added");
        testIt();
    }//GEN-LAST:event_svcAddButtonActionPerformed

    private void exitChocAn(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitChocAn
        try {
            Id.singletonId(chocAnId).destroy();
        } catch (IOException ex) {
            //Error handling here
        }


    }//GEN-LAST:event_exitChocAn

    private void svcUpSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcUpSearchButtonActionPerformed
        ServiceCode s = null;
        int i = Integer.parseInt(svcUpNumText.getText().trim());
        s = (ServiceCode) svcMan.search(i);
        if (s == null) {
            globalMessageLabel.setText("Service Code not found.");
        } else {
            svcUpDescText.setText(s.getDescription());
            svcUpFeeText.setText(String.valueOf(s.getFee()));
        }
    }//GEN-LAST:event_svcUpSearchButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ChocAnUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ChocAnPanel;
    private javax.swing.JPanel MemberTabbedPanel;
    private javax.swing.JPanel ProviderTabbedPanel;
    private javax.swing.JPanel ReportsTabbedPanel;
    private javax.swing.JPanel ServiceCodeTabbedPanel;
    private javax.swing.JPanel TerminalTabbedPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField addressText1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabel1;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField cityText1;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextField descText;
    private javax.swing.JLabel feeLabel;
    private javax.swing.JTextField feeText;
    private javax.swing.JLabel globalMessageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton memberAddButton;
    private javax.swing.JButton memberAddButton1;
    private javax.swing.JPanel memberAddPanel;
    private javax.swing.JPanel memberAddPanel1;
    private javax.swing.JTabbedPane memberDataManagerPanels;
    private javax.swing.JPanel memberDeletePanel;
    private javax.swing.JPanel memberUpdatePanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel stateLabel1;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField stateText1;
    private javax.swing.JButton svcAddButton;
    private javax.swing.JPanel svcAddPanel;
    private javax.swing.JTabbedPane svcDataManagerPanels;
    private javax.swing.JPanel svcDeletePanel;
    private javax.swing.JLabel svcUpDescLabel;
    private javax.swing.JTextField svcUpDescText;
    private javax.swing.JLabel svcUpFeeLabel;
    private javax.swing.JTextField svcUpFeeText;
    private javax.swing.JLabel svcUpNumLabel;
    private javax.swing.JTextField svcUpNumText;
    private javax.swing.JButton svcUpSearchButton;
    private javax.swing.JButton svcUpdateButton;
    private javax.swing.JPanel svcUpdatePanel;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JLabel zipLabel1;
    private javax.swing.JTextField zipText;
    private javax.swing.JTextField zipText1;
    // End of variables declaration//GEN-END:variables

}
